### ISSUE TITLE
Failed to process Spec2006 results

### ISSUE THREAD

**Issue by 040840308** [vusec/floatzone#1]
Hi,
       With the command "python3 run.py run spec2006 default_O2 asan_O2 floatzone_O2 --build --parallel=proc --parallelmax=1", I have successfully run the SPEC 2006 dataset and collected some results. 
        However, when run the command "python3 run.py report spec2006 results/run.2023-06-20.15-37-32/ --aggregate geomean --field runtime:median maxrss:median", I encountered the following errors:
        `/home/test/floatzone/instrumentation-infra/
/home/test/floatzone/spec06/spec2006/result/CPU2006.098.log
01:41:32 [CRITICAL] unkown error
Traceback (most recent call last):
  File "/home/test/floatzone/instrumentation-infra/infra/setup.py", line 315, in _run_command
    self.commands[self.ctx.args.command].run(self.ctx)
  File "/home/test/floatzone/instrumentation-infra/infra/commands/report.py", line 152, in run
    results = parse_logs(ctx, target, instances, a.rundirs,
  File "/home/test/floatzone/instrumentation-infra/infra/commands/report.py", line 543, in parse_logs
    fresults = list(target.parse_outfile(ctx, iname, path))
  File "/home/test/floatzone/instrumentation-infra/infra/targets/spec2006/__init__.py", line 659, in parse_outfile
    yield from parse_logfile(logpath)
  File "/home/test/floatzone/instrumentation-infra/infra/targets/spec2006/__init__.py", line 587, in parse_logfile
    assert m, 'could not find hostname'
AssertionError: could not find hostname`

         Could you help me figure out what happened? I run the floatzone on ubuntu 20.04, with python 3.8. Is the environment all right?

          Thanks!

**Comment by fcgorter** [comment]
Hi,
It looks like the report command cannot find the SPEC log file, or it does not contain the expected output.
The file should live in the spec2006 source directory, e.g.: /home/ubuntu/floatzone/spec2006/result/CPU2006.116.log
SPEC2006 should generate these log files for each benchmark program.
Can you confirm these files exist after you run SPEC?
The first line in such a file should be something like `runspec v6674 started at Thu Oct  6 12:47:26 2022 on "i7-11700"`
That's what the report command is looking for.
